version: '2'
services:
  cache:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: mysql
    ports:
      - "3506:3506"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gopub
  web:
    image: yejiancong/beego
    volumes:
      - .:/go/src/github.com/yejiancong/goshop
    working_dir: /go/src/github.com/yejiancong/goshop
    command: bee run
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache